### ISSUE TITLE
Demos don't run by default because of path issues

### ISSUE THREAD

**Issue by kenchris** [PolymerLabs/lit-element#12]
The demo in demo/lit-element.html doesn't work by default because ../lit-element.js refers to dependencies in ../../ instead of ./node_modules/

**Comment by abdonrd** [comment]
I have the same issue!

**Comment by sorvell** [comment]
This should be [fixed](https://github.com/PolymerLabs/lit-element/blob/master/demo/lit-element.html#L13) now. If not, feel free to re-open.
