### ISSUE TITLE
Property-less lit-elements are not rendered

### ISSUE THREAD

**Issue by ernsheong** [PolymerLabs/lit-element#17]
On 0.1.1, it looks like a `lit-element` without any properties are not rendered at all. At least one property is required to trigger the render? Seems like a bug.

**Comment by notwaldorf** [comment]
Hmm, I can't repro this. Here's a glitch ([code](https://glitch.com/edit/#!/resolute-watcher?path=public/a-thing.js:3:0), [demo](https://resolute-watcher.glitch.me/)) where I'm just rendering the following element, and it shows up fine:

```js
class AThing extends LitElement {
  static get is() {
    return 'a-thing';
  }
  render() {
    return html`
      hi! this is a thing.
    `;
  }
}
window.customElements.define(AThing.is, AThing);
```

Based your initial issue title, I also included in the demo rendering two nested, no-properties elements, and that works fine too.

**Comment by ernsheong** [comment]
Thanks for the response and time taken to triage, @notwaldorf. I will reopen this if I can reproduce this in a glitch.

In my project, I had an empty properties object returned like this:

```js
static get properties() {
  return {};
}
```

which caused a no render. Filling it with at least a property helped. Couldn't immediately reproduce this in a Glitch, I will play with it again and see.

**Comment by notwaldorf** [comment]
I think that if you just return `{}`, you don't really need to add that properties block :)
