### ISSUE TITLE
Support for observers and computed properties

### ISSUE THREAD

**Issue by ernsheong** [PolymerLabs/lit-element#30]
Will there be support for observers and computed properties as described in https://www.polymer-project.org/2.0/docs/devguide/observers? (They do not seem to be currently supported)

**Comment by ernsheong** [comment]
https://github.com/kenchris/lit-element/issues/15 offers a way to implement own observers in a render callback.

I suppose computedProperties can easily be done by doing `${this._compute(fieldName)}` in own instance method.

**Comment by sorvell** [comment]
We currently do not plan to add observers of computed properties. The idea is that you should generally use `_render` and if necessary `_didRender`.

Our experience from `PolymerElement` has led us to believe that providing a library feature ("observers") to route changes to specific functions is not a good return on investment v. letting users just write the necessary code.

The reason for omitting "computed properties" is similar. In general, you can compute necessary values for rendering directly in `_render`. If you have computed public properties, these should not provoke rendering (not be in `properties`) and can be set in `_didRender`.

**Comment by seaneking** [comment]
Definitely agree that listing observers in property config in PolymerElement, rather than handling it functionally, was kinda nasty. But for the use-case of reacting to properties that shouldn't cause a render, would it make sense to document the `_propertiesChanged` callback from Polymer's property mixin in LitElement (perhaps as part of #37)? 

I know that you can just use `_didRender` and not bother with excluding them in `_shouldRender`, but it's not intuitive, due to naming if nothing else.

**Comment by myfreeweb** [comment]
For properties that don't cause a render *directly*, setters seem to be a good replacement. I'm currently porting an app to LitElement, the app uses `app-route`, so for an element that used to have an observer on the `route` passed into it, I now have

```js
  set route (route) {
    fetch(`some/thing/${route.path}`).then(resp => {
      this.someDeclaredProperty = somethingBasedOn(resp)
    })
  }
```

And everything re-renders correctly after the fetch is done.

**Comment by mkozak0108** [comment]
It's okay to replace observers with setters but getters lack memorization from Polymer computed properties. 
If you access getter property multiple times from render it will be calculated each time. Even if you cache getter value inside render function it is still calculated on each render and not when dependent properties has changed.

For now I'm using my own decorator [Gist](https://gist.github.com/mkozak0108/410a8592ed1b44d58f33474016a03fbf)

But I think it would be great to have something similar from lit-element module
```js
@computed('firstName', 'lastName')
get fullName() {
  return `${this.firstName} ${this.lastName}`.trim();
}
```

**Comment by daKmoR** [comment]
probably best to use `update` for it

e.g.
```
update(changedProperties) {
  super.update(changedProperties);
  if (changedProperties.has('firstName') || changedProperties.has('lastName') {
    this.fullName = `${this.firstName} ${this.lastName}`.trim();
  }
}
```

- no need for an extra decorators
- will only be updated once if any of the involved properties changed
- access it does not involve a function call

**Comment by daKmoR** [comment]
actually, I was soooo wrong 🙈 

`update` is already patched e.g. it's not sync... 

I could not find a public api that allows for sync `logging` or `computed properties`.

Opened a new issue https://github.com/Polymer/lit-element/issues/643

**Comment by cristinecula** [comment]
You can achieve something similar to Polymer with this mixin:
```
const PropertyComputing = (base) => class extends base {
  updated(changedProperties) {
    super.updated(changedProperties);
    Object.entries(this.constructor.properties)
      .filter(([key, value]) => typeof value.compute === 'string')
      .forEach(([key, value]) => {
        if(value.deps.some(k => changedProperties.has(k))) {
          this[key] = this[value.compute](...value.deps.map(dep => this[dep]))
        }
      })
  }
}

class MyElement extends PropertyComputing(LitElement) {
  static get properties() {
    return {
      prop1: { type: Number },
      prop2: { type: Number },
      comp: { type: Number, deps: ['prop1', 'prop2'], compute: '_computeComp'},      
      comp2: { type: Number, deps: ['prop1', 'comp'], compute: '_computeComp2'},
    };
  }
```

https://stackblitz.com/edit/sbcgaj?file=my-element.js
