### ISSUE TITLE
Support or document non-generated accessors.

### ISSUE THREAD

**Issue by justinfagnani** [PolymerLabs/lit-element#6]
We should make sure that handwritten accessors are fully supported, documented, and tested.

I assume this much works to delegate state to Polymer, but does it properly call `render()`?

```ts
class MyElement extends LitElement {
  get foo() { return this._getProperty('foo'); }
  set foo(v) { this._setProperty('foo'); }

  render() {
    return html`foo: ${this.foo}`;
  }
}
```

**Comment by sorvell** [comment]
This is supported and [tested](https://github.com/PolymerLabs/lit-element/blob/master/src/test/lit-element_test.ts#L155).

**Comment by nonmetalhail** [comment]
It would be lovely if you could add this to the documentation :)
